# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
      - uses: actions/setup-go@v4
        name: Run commands
        id: runcmd
        with:
          go-version: '1.16.1'
          arch: aarch64
          distro: ubuntu20.04
          run: |
            cd
            go install -v -tags "with_acme with_clash_api with_quic with_grpc with_wireguard with_ech with_utls with_gvisor with_shadowsocksr with_low_memory" github.com/sagernet/sing-box/cmd/sing-box@dev-next
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sing-box-aarch64
          path: sing-box*
